<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250707171134 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activities (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED NOT NULL, event VARCHAR(100) NOT NULL, subject VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B5F1AFE5A76ED395 (user_id), INDEX IDX_B5F1AFE53BAE0AA7 (event), INDEX IDX_B5F1AFE5FBCE3E7A (subject), INDEX IDX_B5F1AFE57B00651C (status), INDEX IDX_B5F1AFE58B8E8428 (created_at), INDEX IDX_B5F1AFE543625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE authentications (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED NOT NULL, type VARCHAR(100) NOT NULL, credential VARCHAR(191) NOT NULL, token VARCHAR(191) NOT NULL, expired_at DATETIME DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D8FCF563A76ED395 (user_id), INDEX IDX_D8FCF5638CDE5729 (type), INDEX IDX_D8FCF56357F1D4B (credential), INDEX IDX_D8FCF5635F37A13B (token), INDEX IDX_D8FCF563C253ECC4 (expired_at), INDEX IDX_D8FCF5637B00651C (status), INDEX IDX_D8FCF5638B8E8428 (created_at), INDEX IDX_D8FCF56343625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE brands (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_7EA24434C53D045F (image), INDEX IDX_7EA244345E237E06 (name), INDEX IDX_7EA244347B00651C (status), INDEX IDX_7EA244348B8E8428 (created_at), INDEX IDX_7EA2443443625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categories (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, displayed SMALLINT UNSIGNED DEFAULT 1 NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_3AF34668C53D045F (image), INDEX IDX_3AF346685E237E06 (name), INDEX IDX_3AF346687B00651C (status), INDEX IDX_3AF346688B8E8428 (created_at), INDEX IDX_3AF3466843625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE colours (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_6728D8D977153098 (code), INDEX IDX_6728D8D95E237E06 (name), INDEX IDX_6728D8D97B00651C (status), INDEX IDX_6728D8D98B8E8428 (created_at), INDEX IDX_6728D8D943625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletters (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, ip_address VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_8ECF000C22FFD58C (ip_address), INDEX IDX_8ECF000CE7927C74 (email), INDEX IDX_8ECF000C7B00651C (status), INDEX IDX_8ECF000C8B8E8428 (created_at), INDEX IDX_8ECF000C43625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED NOT NULL, payment_id BIGINT UNSIGNED DEFAULT NULL, invoice_number VARCHAR(255) DEFAULT NULL, total_item INT UNSIGNED DEFAULT 0 NOT NULL, subtotal NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, total_discount NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, total_taxes NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, total_shipment NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, total_paid NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E52FFDEEA76ED395 (user_id), INDEX IDX_E52FFDEE4C3A3BB (payment_id), INDEX IDX_E52FFDEE2DA68207 (invoice_number), INDEX IDX_E52FFDEE6103B6E3 (total_item), INDEX IDX_E52FFDEEB89C0E84 (subtotal), INDEX IDX_E52FFDEE5F1FB8BF (total_discount), INDEX IDX_E52FFDEE1FC31CA (total_taxes), INDEX IDX_E52FFDEEBC342C6D (total_shipment), INDEX IDX_E52FFDEE839638C5 (total_paid), INDEX IDX_E52FFDEE7B00651C (status), INDEX IDX_E52FFDEE8B8E8428 (created_at), INDEX IDX_E52FFDEE43625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders_carts (order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, INDEX IDX_FAAE50D8D9F6D38 (order_id), INDEX IDX_FAAE50D4584665A (product_id), PRIMARY KEY(order_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders_billings (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, order_id BIGINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_EAC77A778D9F6D38 (order_id), INDEX IDX_EAC77A775E237E06 (name), INDEX IDX_EAC77A777B00651C (status), INDEX IDX_EAC77A778B8E8428 (created_at), INDEX IDX_EAC77A7743625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders_details (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, order_id BIGINT UNSIGNED NOT NULL, inventory_id BIGINT UNSIGNED NOT NULL, price NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, qty INT UNSIGNED DEFAULT 0 NOT NULL, total NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_835379F18D9F6D38 (order_id), INDEX IDX_835379F19EEA759 (inventory_id), INDEX IDX_835379F1CAC822D9 (price), INDEX IDX_835379F1C8F8AE1F (qty), INDEX IDX_835379F1C22FE15E (total), INDEX IDX_835379F17B00651C (status), INDEX IDX_835379F18B8E8428 (created_at), INDEX IDX_835379F143625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_65D29B32C53D045F (image), INDEX IDX_65D29B325E237E06 (name), INDEX IDX_65D29B327B00651C (status), INDEX IDX_65D29B328B8E8428 (created_at), INDEX IDX_65D29B3243625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, brand_id BIGINT UNSIGNED NOT NULL, image VARCHAR(255) NOT NULL, sku VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, price NUMERIC(18, 4) UNSIGNED DEFAULT \'0\' NOT NULL, total_order INT UNSIGNED DEFAULT 0 NOT NULL, total_rating INT UNSIGNED DEFAULT 0 NOT NULL, details LONGTEXT NOT NULL, description LONGTEXT NOT NULL, published_date DATETIME DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B3BA5A5A44F5D008 (brand_id), INDEX IDX_B3BA5A5AF9038C4 (sku), INDEX IDX_B3BA5A5AC53D045F (image), INDEX IDX_B3BA5A5A5E237E06 (name), INDEX IDX_B3BA5A5ACAC822D9 (price), INDEX IDX_B3BA5A5A365B05AA (total_order), INDEX IDX_B3BA5A5A109D0534 (total_rating), INDEX IDX_B3BA5A5A7B00651C (status), INDEX IDX_B3BA5A5A8B8E8428 (created_at), INDEX IDX_B3BA5A5A43625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_wishlists (product_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, INDEX IDX_1831CD3D4584665A (product_id), INDEX IDX_1831CD3DA76ED395 (user_id), PRIMARY KEY(product_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_categories (product_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NOT NULL, INDEX IDX_E8ACBE764584665A (product_id), INDEX IDX_E8ACBE7612469DE2 (category_id), PRIMARY KEY(product_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_images (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, product_id BIGINT UNSIGNED NOT NULL, path VARCHAR(255) NOT NULL, sort INT UNSIGNED DEFAULT 0 NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_662C35404584665A (product_id), INDEX IDX_662C3540B548B0F (path), INDEX IDX_662C35405124F222 (sort), INDEX IDX_662C35407B00651C (status), INDEX IDX_662C35408B8E8428 (created_at), INDEX IDX_662C354043625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_inventories (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, product_id BIGINT UNSIGNED NOT NULL, size_id BIGINT UNSIGNED NOT NULL, colour_id BIGINT UNSIGNED NOT NULL, stock INT UNSIGNED DEFAULT 0 NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_69B1E4A64584665A (product_id), INDEX IDX_69B1E4A6498DA827 (size_id), INDEX IDX_69B1E4A6569C9B4C (colour_id), INDEX IDX_69B1E4A64B365660 (stock), INDEX IDX_69B1E4A67B00651C (status), INDEX IDX_69B1E4A68B8E8428 (created_at), INDEX IDX_69B1E4A643625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_reviews (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, product_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, rating INT UNSIGNED DEFAULT 0 NOT NULL, review LONGTEXT NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B24D11524584665A (product_id), INDEX IDX_B24D1152A76ED395 (user_id), INDEX IDX_B24D1152D8892622 (rating), INDEX IDX_B24D11527B00651C (status), INDEX IDX_B24D11528B8E8428 (created_at), INDEX IDX_B24D115243625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE settings (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, key_name VARCHAR(255) NOT NULL, key_value TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E545A0C5D824A5CF (key_name), INDEX IDX_E545A0C57B00651C (status), INDEX IDX_E545A0C58B8E8428 (created_at), INDEX IDX_E545A0C543625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sizes (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B69E87695E237E06 (name), INDEX IDX_B69E87697B00651C (status), INDEX IDX_B69E87698B8E8428 (created_at), INDEX IDX_B69E876943625D9F (updated_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, image VARCHAR(255) DEFAULT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(191) DEFAULT NULL, last_name VARCHAR(191) DEFAULT NULL, gender VARCHAR(10) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(191) DEFAULT NULL, address TEXT DEFAULT NULL, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, status SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_1483A5E9C53D045F (image), INDEX IDX_1483A5E9A9D1C132 (first_name), INDEX IDX_1483A5E9C808BA5A (last_name), INDEX IDX_1483A5E9C7470A42 (gender), INDEX IDX_1483A5E92D5B0234 (city), INDEX IDX_1483A5E95373C966 (country), INDEX IDX_1483A5E9A1ACE158 (zip_code), INDEX IDX_1483A5E9D4E6F81 (address), INDEX IDX_1483A5E935C246D5 (password), INDEX IDX_1483A5E97B00651C (status), INDEX IDX_1483A5E98B8E8428 (created_at), INDEX IDX_1483A5E943625D9F (updated_at), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), UNIQUE INDEX UNIQ_IDENTIFIER_PHONE (phone), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE authentications ADD CONSTRAINT FK_D8FCF563A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id)');
        $this->addSql('ALTER TABLE orders_carts ADD CONSTRAINT FK_FAAE50D8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE orders_carts ADD CONSTRAINT FK_FAAE50D4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE orders_billings ADD CONSTRAINT FK_EAC77A778D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE orders_details ADD CONSTRAINT FK_835379F18D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE orders_details ADD CONSTRAINT FK_835379F19EEA759 FOREIGN KEY (inventory_id) REFERENCES products_inventories (id)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A44F5D008 FOREIGN KEY (brand_id) REFERENCES brands (id)');
        $this->addSql('ALTER TABLE products_wishlists ADD CONSTRAINT FK_1831CD3D4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_wishlists ADD CONSTRAINT FK_1831CD3DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE products_categories ADD CONSTRAINT FK_E8ACBE764584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_categories ADD CONSTRAINT FK_E8ACBE7612469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE products_images ADD CONSTRAINT FK_662C35404584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_inventories ADD CONSTRAINT FK_69B1E4A64584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_inventories ADD CONSTRAINT FK_69B1E4A6498DA827 FOREIGN KEY (size_id) REFERENCES sizes (id)');
        $this->addSql('ALTER TABLE products_inventories ADD CONSTRAINT FK_69B1E4A6569C9B4C FOREIGN KEY (colour_id) REFERENCES colours (id)');
        $this->addSql('ALTER TABLE products_reviews ADD CONSTRAINT FK_B24D11524584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_reviews ADD CONSTRAINT FK_B24D1152A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY FK_B5F1AFE5A76ED395');
        $this->addSql('ALTER TABLE authentications DROP FOREIGN KEY FK_D8FCF563A76ED395');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEA76ED395');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE4C3A3BB');
        $this->addSql('ALTER TABLE orders_carts DROP FOREIGN KEY FK_FAAE50D8D9F6D38');
        $this->addSql('ALTER TABLE orders_carts DROP FOREIGN KEY FK_FAAE50D4584665A');
        $this->addSql('ALTER TABLE orders_billings DROP FOREIGN KEY FK_EAC77A778D9F6D38');
        $this->addSql('ALTER TABLE orders_details DROP FOREIGN KEY FK_835379F18D9F6D38');
        $this->addSql('ALTER TABLE orders_details DROP FOREIGN KEY FK_835379F19EEA759');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A44F5D008');
        $this->addSql('ALTER TABLE products_wishlists DROP FOREIGN KEY FK_1831CD3D4584665A');
        $this->addSql('ALTER TABLE products_wishlists DROP FOREIGN KEY FK_1831CD3DA76ED395');
        $this->addSql('ALTER TABLE products_categories DROP FOREIGN KEY FK_E8ACBE764584665A');
        $this->addSql('ALTER TABLE products_categories DROP FOREIGN KEY FK_E8ACBE7612469DE2');
        $this->addSql('ALTER TABLE products_images DROP FOREIGN KEY FK_662C35404584665A');
        $this->addSql('ALTER TABLE products_inventories DROP FOREIGN KEY FK_69B1E4A64584665A');
        $this->addSql('ALTER TABLE products_inventories DROP FOREIGN KEY FK_69B1E4A6498DA827');
        $this->addSql('ALTER TABLE products_inventories DROP FOREIGN KEY FK_69B1E4A6569C9B4C');
        $this->addSql('ALTER TABLE products_reviews DROP FOREIGN KEY FK_B24D11524584665A');
        $this->addSql('ALTER TABLE products_reviews DROP FOREIGN KEY FK_B24D1152A76ED395');
        $this->addSql('DROP TABLE activities');
        $this->addSql('DROP TABLE authentications');
        $this->addSql('DROP TABLE brands');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE colours');
        $this->addSql('DROP TABLE newsletters');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE orders_carts');
        $this->addSql('DROP TABLE orders_billings');
        $this->addSql('DROP TABLE orders_details');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE products_wishlists');
        $this->addSql('DROP TABLE products_categories');
        $this->addSql('DROP TABLE products_images');
        $this->addSql('DROP TABLE products_inventories');
        $this->addSql('DROP TABLE products_reviews');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE sizes');
        $this->addSql('DROP TABLE users');
    }
}
